[theme]
base="light"
primaryColor="#006400"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
headless = true
port = $PORT
enableCORS = false
" > ~/.streamlit/config.toml